version: '3.8'

services:
  client_1:
    environment:
      - ID=0
      - PORT=5000
    build: .

  client_2:
    environment:
      - ID=1
      - PORT=5001
    build: .

  client_3:
    environment:
      - ID=2
      - PORT=5002
    build: .

  client_4:
    environment:
      - ID=3
      - PORT=5003
    build: .

  client_5:
    environment:
      - ID=4
      - PORT=5004
    build: .

