version: '3.8'

services:
  container_1:
    environment:
      - ID=0
      - PORT=5000
      - CLUSTER_PORT=6000
    ports:
      - "5000:5000"
      - "6000:6000"
    build: .
    volumes:
      - ./shared_data:/shared

  container_2:
    environment:
      - ID=1
      - PORT=5001
      - CLUSTER_PORT=6001
    ports:
      - "5001:5001"
      - "6001:6001"
    build: .
    volumes:
      - ./shared_data:/shared

  container_3:
    environment:
      - ID=2
      - PORT=5002
      - CLUSTER_PORT=6002
    ports:
      - "5002:5002"
      - "6002:6002"
    build: .
    volumes:
      - ./shared_data:/shared

  container_4:
    environment:
      - ID=3
      - PORT=5003
      - CLUSTER_PORT=6003
    ports:
      - "5003:5003"
      - "6003:6003"
    build: .
    volumes:
      - ./shared_data:/shared

  container_5:
    environment:
      - ID=4
      - PORT=5004
      - CLUSTER_PORT=6004
    ports:
      - "5004:5004"
      - "6004:6004"
    build: .
    volumes:
      - ./shared_data:/shared
